[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
bytecode_hash = "none"
via_ir = true
optimizer = true
optimizer_runs = 1000000
fs_permissions = [{ access = "read-write", path = "./" }]

[profile.default.fuzz]
runs = 1000

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "${ETHERSCAN_URL}" }
optimism = { key = "${OPTIMISTICSCAN_API_KEY}", url = "${OPTIMISTICSCAN_URL}" }
polygon = { key = "${POLYGONSCAN_API_KEY}", url = "${POLYGONSCAN_URL}" }
base = { key = "${BASESCAN_API_KEY}", url = "${BASESCAN_URL}" }
arbitrum = { key = "${ARBISCAN_API_KEY}", url = "${ARBISCAN_URL}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
